---
new_page_extension: md
auto_deploy: true
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: _data
  label: Content
  create: documents
  match: "**/*.yml"
upload_dir: forestryio/images
public_path: "{{ site.baseurl }}/forestryio/images"
front_matter_path: "/forestryio/images"
use_front_matter_path: true
file_template: ":filename:"
